version : "3"
services:
  db:
    build: db
    environment:
      - MYSQL_ROOT_PASSWORD=wasbook
      - MYSQL_USER=wasbook
      - MYSQL_PASSWORD=wasbook
      - TZ=Asia/Tokyo
    networks:
      internal:
  
  apache:
    build: apache
    environment:
      - MYSQL_HOST=db
      - TZ=Asia/Tokyo
    # ポリュームを指定する場合の設定例。コンテンツは別途配置すること
    # volumes:
    #  - ../wasbook-contents:/var/www
    ports:
      # PROXY(Forward PROXY)用ポート。環境変数 APACHE_PORXY_PORT によりカスタマイズ可能
      - ${APACHE_IP:-127.0.0.1}:${APACHE_PROXY_PORT:-13128}:3128
      # 以下はデバッグ用
      # - ${APACHE_IP:-127.0.0.1}:${APACHE_WEB_PORT:-10080}:80
    networks:
      internal:
    
  nginx:
    build: nginx
    # Nginxを直接公開する場合は以下の3行を有効化する
    # ports:
    #  - ${WEB_IP:-127.0.0.1}:80:80
    #  - ${WEB_IP:-127.0.0.1}:443:443
    depends_on:
      apache:
        condition: service_started    
      mail:
        condition: service_started
      tomcat:
        condition: service_started
    networks:
      internal:
        aliases:
          - example.jp
          - api.example.net
          - trap.example.com
          - internal.example.jp

  tomcat:
    build: tomcat
    # この ports 指定はデバッグ用なので通常は指定しない
    # ports:
    #  - ${WEB_IP:-127.0.0.1}:8080:8080
    networks:
      internal:

  mail:
    build: mail
    # この ports 指定はデバッグ用なので通常は指定しない
    # ports:
    #  - 127.0.0.1:3380:80
    environment:
      - HTTPPATH=/mail
    networks:
      internal:

networks:
  internal:
